import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import Footer from "./components/Footer";
import './globals.css'
import { AuthContextProvider } from "./context/AuthContext";
import { Toaster } from "react-hot-toast";
import NavbarWrapper from "./components/NavbarWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Halawany App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AuthContextProvider>
        <NavbarWrapper/>
          {children}
          <Footer />
        </AuthContextProvider>

        <Toaster />
      </body>
    </html>
  );
}

// {"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmNkNWM0M2IxOGEzOGE4YzAxOTdkYiIsImVtYWlsIjoibXloQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ1NDM4MDc3LCJleHAiOjE3NDgwMzAwNzd9.Oj7VAknvbWs1T87gOJvqESMDTEAtbO0Agu_QGvdNuTM","email":"myh@gmail.com"}